# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e4ce949d014ef802cf9685ba55c8a607"
name = "beneficial-merchandise-app"
handle = "beneficial-merchandise-app-13"
application_url = "https://amazing-sophisticated-incident-rd.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products"

[auth]
redirect_urls = [
  "https://amazing-sophisticated-incident-rd.trycloudflare.com/auth/callback",
  "https://amazing-sophisticated-incident-rd.trycloudflare.com/auth/shopify/callback",
  "https://amazing-sophisticated-incident-rd.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
